In [7]:
#Numpy Arrays
import numpy as np
x = np.array(["A",67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [9]:
a = np.array([10,20,30,40])
print(a)
print(type(a))

[10 20 30 40]
<class 'numpy.ndarray'>


In [11]:
#Reshaping an array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [15]:
#Create an array with arange()
c = np.arange(3,20)
print(c)
type(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [17]:
d = np.array([1.3467, 3.10987, 4.91236])
np.around(d,2)

array([1.35, 3.11, 4.91])

In [19]:
print(np.sqrt(d))

[1.16047404 1.76348235 2.21638444]


In [21]:
print(np.around(np.sqrt(d),2))

[1.16 1.76 2.22]


In [23]:
#2D Array
a1 = np.array([[3,4,5,8],[7,2,8, np.NAN]])
a1_copy1 = a1.astype(float)
a1_copy1.dtype

dtype('float64')

In [27]:
a1 = np.array([[3,4,5,8],[7,2,8, np.NAN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [29]:
a1_copy1 = a1.astype(str)
a1_copy1

array([['3.0', '4.0', '5.0', '8.0'],
       ['7.0', '2.0', '8.0', 'nan']], dtype='<U32')

In [31]:
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [33]:
a2 = np.array([[3,4,6],[7,8,9],[4,6,10]])
a2

array([[ 3,  4,  6],
       [ 7,  8,  9],
       [ 4,  6, 10]])

In [39]:
print(a2.sum(axis = 0))
print(a2.sum(axis = 1))

[14 18 25]
[13 24 20]


In [43]:
print(a2)
print(np.mean(a2, axis = 0))
print(np.mean(a2, axis = 1))

[[ 3  4  6]
 [ 7  8  9]
 [ 4  6 10]]
[4.66666667 6.         8.33333333]
[4.33333333 8.         6.66666667]


In [47]:
#Matrix Operations
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [53]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])


In [59]:
C = np.matmul(A, B)
print(C)

[[19 22]
 [43 50]]


In [57]:
print(A. T)
print(B. T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [61]:
a4 = np.array([[3,4,5],[7,2,8],[9,2,1],[10,9,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  2,  1],
       [10,  9, 18]])

In [63]:
a4[0::3,0::2]

array([[ 3,  5],
       [10, 18]])

In [69]:
#Slicing of array
a4[1:3]

array([[7, 2, 8],
       [9, 2, 1]])